//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dondeeshoyEntities : DbContext
    {
        public dondeeshoyEntities()
            : base("name=dondeeshoyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<establishments> establishments { get; set; }
        public DbSet<establishments_accounts> establishments_accounts { get; set; }
        public DbSet<establishments_accounts_logs> establishments_accounts_logs { get; set; }
        public DbSet<establishments_type> establishments_type { get; set; }
        public DbSet<locals> locals { get; set; }
        public DbSet<promos_events> promos_events { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<users_favorites_establishments> users_favorites_establishments { get; set; }
    }
}
