//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class establishments_type
    {
        public establishments_type()
        {
            this.establishments = new HashSet<establishments>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<establishments> establishments { get; set; }
    }
}
