//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class establishments_accounts
    {
        public establishments_accounts()
        {
            this.establishments_accounts_logs = new HashSet<establishments_accounts_logs>();
        }
    
        public int id { get; set; }
        public int establishment { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
    
        public virtual establishments establishments { get; set; }
        public virtual ICollection<establishments_accounts_logs> establishments_accounts_logs { get; set; }
    }
}
