//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class establishments
    {
        public establishments()
        {
            this.establishments_accounts = new HashSet<establishments_accounts>();
            this.locals = new HashSet<locals>();
            this.promos_events = new HashSet<promos_events>();
            this.users_favorites_establishments = new HashSet<users_favorites_establishments>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> establishment_type { get; set; }
        public string imagebase64 { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<establishments_accounts> establishments_accounts { get; set; }
        public virtual establishments_type establishments_type { get; set; }
        public virtual ICollection<locals> locals { get; set; }
        public virtual ICollection<promos_events> promos_events { get; set; }
        public virtual ICollection<users_favorites_establishments> users_favorites_establishments { get; set; }
    }
}
