//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class locals_promos_events
    {
        public int id { get; set; }
        public int promo_event { get; set; }
        public int local { get; set; }
    
        public virtual locals locals { get; set; }
        public virtual promos_events promos_events { get; set; }
    }
}
