//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.users_favorites_establishments = new HashSet<users_favorites_establishments>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string lastName { get; set; }
    
        public virtual ICollection<users_favorites_establishments> users_favorites_establishments { get; set; }
    }
}
